version: "3.8"

services:
  friendease-web:
    image: friendease-web:latest
    container_name: friendease-web
    restart: always
    ports:
      - "3001:3001/tcp"
    environment:
      - VITE_BASE_API_URL=http://localhost:3000
